### ISSUE TITLE
Outdated code and rethinking submodules

### ISSUE THREAD

**Issue by thatging3rkid** [FIRST-Team-1699/team-1699-utils#13]
Last time we tried working with submodules, we had issues with the submodules not playing well with existing source code. But, because there is no "source code" in this repo, just copies of code that exist in other repos, wouldn't it make sense to convert this repo into a bunch of submodules?

discuss...

Also, feel free to add people to the discussion.

Or even better: a script that downloads the most recent versions of the repos into your project, and adds them to the .gitignore

**Comment by squirlemaster42** [comment]
I originally build this to imitate 254, they put all of their code in their project for the year with all of their robot code. We can look at submodules. For now I am going to keep putting ideas in this repo and try to get it ready for this year. If I have someone who I can put on submodules I will

**Comment by thatging3rkid** [comment]
So, was the intent of this repo to be a place where you could easily download some of the smaller projects, or a place to put super experimental test code? I think it would be good to have both, but I remembered one of the problems with submodules; they only link to a certain commit. A script that downloads them would solve that, and would be relatively quick to write up. But, I think that we need to agree on which one of these this repo is, and think about the other option.

**Comment by thatging3rkid** [comment]
This will be solved with the git repo manager I am working on, it should be out soon-ish.
