### ISSUE TITLE
Package hierarchy is not correct

### ISSUE THREAD

**Issue by thatging3rkid** [FIRST-Team-1699/Team-1699-Utils#8]
Standard hierarchy is org.usfirst.frc.team1699, we are currently using frc.team1699. This effects all branches. Is this intended or a mistake?

**Comment by squirlemaster42** [comment]
Not necessarily intended and can be changed.

**Comment by squirlemaster42** [comment]
Most likely will stay the same to limit number of folders created. For example frc.team1699 creates 2 folders while org.usfirst.frc.team1699 creates 4.
