### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by thatging3rkid** [FIRST-Team-1699/team-1699-utils#9]
Should we make a contributing file, convert code to the Google Syntax (rip one-liners), etc?

**Comment by squirlemaster42** [comment]
We can start to do this.

**Comment by squirlemaster42** [comment]
What will the contributing file contain. @thatging3rkid

**Comment by thatging3rkid** [comment]
@squirlemaster42 style sheet, some definitions for comments, etc. I'd suggest looking at WPILib's contributing file.
